name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Adjust PHP version if needed

      - name: Install dependencies
        run: composer install  # If you have any dependencies

      - name: Build script
        run: |
          # Any build commands here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory containing your PHP script
